force-app/main/default/objects/Account/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountRiskChangeEvent__e/AccountRiskChangeEvent__e.object-meta.xml
<CustomObject>
    <label>AccountRiskChangeEvent</label>
    <pluralLabel>AccountsRiskChangeEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountRiskChangeEvent__e/fields/AccountOwnerId__c.field-meta.xml
<CustomField>
    <fullName>AccountOwnerId__c</fullName>
    <label>Account Owner</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
 * @description       : 
 * @author            : Edgar Santillana
 * @group             : 
 * @last modified on  : 08-01-2024
 * @last modified by  : Edgar Santillana
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   08-01-2024   Edgar Santillana   Initial Version
**/
public with sharing class AccountTriggerHandler {
    /**
    * @description 
    * @author Edgar Santillana | 08-01-2024 
    * @param newAccounts 
    * @param oldAccountMap 
    * @param isBefore 
    * @param isInsert 
    * @param isUpdate 
    **/
    public static void handleTrigger(List<Account> newAccounts, Map<Id, Account> oldAccountMap, Boolean isBefore, Boolean isInsert, Boolean isUpdate) {
        if (isBefore) {
            if (isInsert) {
                beforeInsert(newAccounts);
            } else if (isUpdate) {
                beforeUpdate(newAccounts, oldAccountMap);
            }
        } else {
            if (isInsert) {
                afterInsert(newAccounts);
            } else if (isUpdate) {
                afterUpdate(newAccounts, oldAccountMap);
            }
        }
    }

    private static void beforeInsert(List<Account> newAccounts) {
       
    }

    private static void beforeUpdate(List<Account> newAccounts, Map<Id, Account> oldAccountMap) {
       
    }

    private static void afterInsert(List<Account> newAccounts) {
        
    }

    /**
    * @description 
    * @author Edgar Santillana | 08-01-2024 
    * @param newAccounts 
    * @param oldAccountMap 
    **/
    private static void afterUpdate(List<Account> newAccounts, Map<Id, Account> oldAccountMap) {
        List<AccountRiskChangeEvent__e> events = new List<AccountRiskChangeEvent__e>();
        for (Account acc : newAccounts) {
            Account oldAcc = oldAccountMap.get(acc.Id);
            System.debug('Updated Account: ' + acc.Name);
            if (acc.Risk__c != oldAcc.Risk__c && acc.Risk__c == 'High') {
                AccountRiskChangeEvent__e event = new AccountRiskChangeEvent__e(
                    AccountId__c = acc.Id,
                    AccountOwnerId__c = acc.OwnerId
                );
                events.add(event);
            }    
        }

        if (!events.isEmpty()) {
            System.debug('Event was created: ' + events);
            EventBus.publish(events);
        }
    }
}